### ISSUE TITLE
Support for dedupe key

### ISSUE THREAD

**Issue by szunami** [Entle/action-pagerduty-alert#1]
Would you be open to supporting the "dedupe key" field described here:

https://developer.pagerduty.com/api-reference/reference/events-v2/openapiv3.json/paths/~1enqueue/post

Ideally, this would be configurable as an input to the workflow.

I am happy to contribute this, if you're open to it!

**Comment by JohJonker** [comment]
Hi @szunami, thanks for raising this and for contributing the PR! Good idea!

How would you generate the dedup key to supply to `action-pagerduty-alert` in your Actions workflow? We'll need to include an example of that use case in README.

Would you mind adding a README edit to your PR?

**Comment by szunami** [comment]
The dedup_key will depend on your workflow. For example, if you were using Github actions to perform uptime monitoring on a website (just an example!), you could have the dedup_key be "uptime_check". Then, if the uptime check fails multiple times, there will only be one alert.

I just updated the README with some more info.

**Comment by JohJonker** [comment]
Ah, I understand now. So your dedup_key will be fixed for the workflow, make sense. 👍

Could you document that under the "Inputs" and "Example usage" headings of the README?

Thanks for your contribution!

**Comment by JohJonker** [comment]
Thanks for your contribution @szunami! This is now released in [0.2.0](https://github.com/Entle/action-pagerduty-alert/releases/tag/0.2.0).
