### ISSUE TITLE
Warning: Unexpected input(s) 'pagerduty-dedup-key', valid inputs are ['pagerduty-integration-key']

### ISSUE THREAD

**Issue by brianpham** [Entle/action-pagerduty-alert#4]
I see the following warning when the action is used. The alert still get sent successfully though and doesn't seem to actually break anything. 

```
Warning: Unexpected input(s) 'pagerduty-dedup-key', valid inputs are ['pagerduty-integration-key']
```

**Comment by miparnisari** [comment]
@brianpham are you using v0.1.0 or v0.2.0? Support for `pagerduty-dedup-key` was added in 0.2.0

**Comment by andys8** [comment]
PR to fix this: https://github.com/Entle/action-pagerduty-alert/pull/5

**Comment by JohJonker** [comment]
Thanks @miparnisari and @andys8! Fixed in the latest version.
